### PR TITLE
Integrating overview SDL chapter

### PR DESCRIPTION
**Pull request by larsvilhuber**
See notes in commits

### CODE REVIEW

**Review by jimhshen — APPROVED** [review]
Raises the question of do we want 17 bib files (one for each chapter) or one big one for the handbook?

**Comment by larsvilhuber** [comment]
Have a look for any scripts to parse out the "actually used" refernences from the "total references". There are such scripts for Latex.

If you turn off the discavoid.bib file, pandoc will report all the failed references. Those are the ones you need to add back.... there probably is some script to figure that out.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by jimhshen** [comment]
The build is failing after merging it in

https://github.com/jimhshen/admindatahandbook/runs/1157770324

**Comment by larsvilhuber** [comment]
That isn't the version I prepared. Let me check.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by larsvilhuber** [comment]
Try pulling in again.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Pull request merged**
